name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Trigger Docker
        run: |
          sudo docker stop jewelsland-backend-container || true
          sudo docker rm jewelsland-backend-container || true
          echo "${{ secrets.ENV_FILE }}" > .env
          sudo docker run -d --name jewelsland-backend-container -p 443:443 --env-file .env jewelsland-backend:latest
