name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Print Working Directory
        run: pwd

      - name: Write key.pem
        run: |
          echo "${{ secrets.KEY_PEM }}" > ./cert/key.pem

      - name: Write cert.pem
        run: |
          echo "${{ secrets.CERT_PEM }}" > ./cert/cert.pem

      - name: Write .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Trigger Docker
        run: |
          sudo docker stop jewelsland-backend-container || true
          sudo docker rm jewelsland-backend-container || true
          sudo docker run -d --name jewelsland-backend-container -p 443:443 --env-file .env jewelsland-backend:latest

      - name: List Contents of /app/cert in Docker Container
        run: sudo docker exec jewelsland-backend-container ls -la /app/cert
